### ISSUE TITLE
get error report when using heatmap.pl

### ISSUE THREAD

**Issue by liencau** [dekkerlab/cworld-dekker#6]
(perl /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/heatmap.pl -i K5__30000__10.matrix.gz -i GM__30000__10.matrix.gz -o K5__GM__30000__10__median)
I just want to test the script (heatmap.pl),but got error report.
The error report:
Can't load '/NAS7/home/caulien/bin/localperl/lib/site_perl/5.26.0//x86_64-linux/auto/GD/GD.so' for module GD: libiconv.so.2: cannot open shared object file: No such file or directory at /NAS7/home/caulien/bin/localperl/lib//5.26.0/x86_64-linux/DynaLoader.pm line 193.
at /NAS7/home/caulien/bin/localperl/lib/site_perl/5.26.0//x86_64-linux/GD/Simple.pm line 160.
Compilation failed in require at /NAS7/home/caulien/bin/localperl/lib/site_perl/5.26.0//x86_64-linux/GD/Simple.pm line 160.
BEGIN failed--compilation aborted at /NAS7/home/caulien/bin/localperl/lib/site_perl/5.26.0//x86_64-linux/GD/Simple.pm line 160.
Compilation failed in require at /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/heatmap.pl line 13.
BEGIN failed--compilation aborted at /NAS4/lien/Hi-C/scripts_dekkerlab/cworld-dekker-master/scripts/perl/heatmap.pl line 13.

how can I deal with it? Thank you so much!

**Comment by nandankita** [comment]
I think you forgot to export PERL5LIB path in your bashrc file.  Look at this section: https://github.com/dekkerlab/cworld-dekker/#building-and-installing-cworld
